In [2]:
import cv2

In [3]:
def load_image_with_cv2(path, mode = 'rgb'):
    if mode=='grayscale':
        image = cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2GRAY)
    else:
        image = cv2.imread(path)
    return image

In [4]:
image = load_image_with_cv2('./image/test.jpg', mode='grayscale')

In [5]:
cv2.imshow('image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
from pytesseract import pytesseract

def run_pytesseract(image, path_engine, config= '-l eng'):
    pytesseract.tesseract_cmd = path_engine
    result = pytesseract.image_to_string(image, config=config)
    return result

In [7]:
path_engine = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
run_pytesseract(image, path_engine)

'Wwivri\n\naee\n\nIGA 5G Wave2 2A1B\n\n>> KT G\n\nPW >> 8hg79eh832\n\n        \n \n\nOlSGnAMg!\n\nOlu\nfal'

In [8]:
def mapping_function(value,bottom=77,top=157):
    if value < bottom:
        return 0
    elif value > top: 
        return 255
    else:
        return int(255*((value-bottom)/(top-bottom)))

In [9]:
image

array([[ 95,  89,  96, ..., 129, 133, 137],
       [ 98,  91,  97, ..., 131, 133, 136],
       [ 99,  92,  96, ..., 133, 133, 134],
       ...,
       [ 76,  78,  79, ...,  54,  58,  58],
       [ 78,  78,  79, ...,  56,  59,  57],
       [ 80,  79,  78, ...,  63,  66,  64]], dtype=uint8)

In [10]:
import numpy as np

image = [[mapping_function(i) for i in line] for line in image]
image = np.array(image, dtype=np.uint8)

In [14]:
cv2.imshow('image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
run_pytesseract(image, path_engine, config='-l eng+kor')

'wi-ri >> KT_GiGA_5G Wave2_2A1B\nPW >> 8hg79eh832'

In [13]:
run_pytesseract(image, path_engine, config='-l eng+kor --oem 1 --psm 11')

'=~\n\nwi-ri >> KT_GiGA 5G Wave2 2A1B\n\nPW >> 8hg79eh832\n\nf |\n\n필 요 하 신 스 트 로 우 , 냄 퀸\n\n1 |\n\n이 곳 을 이용해\n\n수 세 요 !\n\nSS —'

In [15]:
import pandas as pd

def image2data(path_img):
    data = pytesseract.image_to_data(path_img, config='-l eng+kor --oem 1 --psm 11')
    lines = data.split('\n')
    columns, df_data = None, None
    for i,line in enumerate(lines):
        line = line.split('\t')
        if i==0:
            columns = line.copy()
            df_data = {col:[] for col in line}
            continue
        for col, l in zip(columns,line):
            df_data[col]+=[l]
    return pd.DataFrame(df_data)

In [ ]:
cv2.imwrite('./image/processed_image.jpg', image)

In [16]:
image_data = image2data('./image/processed_image.jpg')
image_data

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,3024,4032,-1,
1,2,1,1,0,0,0,1361,608,531,252,-1,
2,3,1,1,1,0,0,1361,608,531,252,-1,
3,4,1,1,1,1,0,1361,608,531,252,-1,
4,5,1,1,1,1,1,1524,604,167,334,13,-_
5,2,1,2,0,0,0,541,1574,2112,142,-1,
6,3,1,2,1,0,0,541,1574,2112,142,-1,
7,4,1,2,1,1,0,541,1574,2112,142,-1,
8,5,1,2,1,1,1,541,1600,301,69,28,wi-rt
9,5,1,2,1,1,2,900,1586,129,78,90,>>
10,5,1,2,1,1,3,1084,1574,506,116,39,KT_GiIGA
11,5,1,2,1,1,4,1669,1593,160,105,93,5G
12,5,1,2,1,1,5,1901,1597,384,108,91,Wave2
13,5,1,2,1,1,6,2367,1611,286,105,92,2A1B
14,2,1,3,0,0,0,1031,1843,1111,134,-1,
15,3,1,3,1,0,0,1031,1843,1111,134,-1,
16,4,1,3,1,1,0,1031,1843,1111,134,-1,
17,5,1,3,1,1,1,1031,1843,153,95,96,PW
18,5,1,3,1,1,2,1232,1862,123,73,93,>>
19,5,1,3,1,1,3,1405,1856,737,121,88,8hg79eh832
20,2,1,4,0,0,0,941,2327,1018,108,-1,
21,3,1,4,1,0,0,941,2327,1018,108,-1,
22,4,1,4,1,1,0,941,2327,1018,108,-1,
23,5,1,4,1,1,1,941,2327,148,97,93,필
24,5,1,4,1,1,2,1127,2366,47,47,92,요
25,5,1,4,1,1,3,1186,2334,87,80,93,하
26,5,1,4,1,1,4,1282,2339,15,62,93,신
27,5,1,4,1,1,5,1361,2345,133,62,92,스
28,5,1,4,1,1,6,1534,2357,53,78,93,트
29,5,1,4,1,1,7,1632,2350,48,53,93,로
30,5,1,4,1,1,8,1654,2323,51,135,93,우
31,5,1,4,1,1,9,1679,2323,52,135,88,","
32,5,1,4,1,1,10,1787,2354,172,74,14,냄
33,5,1,4,1,1,11,1890,2323,68,135,21,퀸
34,2,1,5,0,0,0,2907,2362,45,88,-1,
35,3,1,5,1,0,0,2907,2362,45,88,-1,
36,4,1,5,1,1,0,2907,2362,45,88,-1,
37,5,1,5,1,1,1,2907,2362,25,88,9,!
38,5,1,5,1,1,2,2946,2366,6,26,86,|
39,2,1,6,0,0,0,1125,2521,573,186,-1,
40,3,1,6,1,0,0,1125,2521,573,186,-1,
41,4,1,6,1,1,0,1125,2521,573,186,-1,
42,5,1,6,1,1,1,1125,2531,136,172,83,이
43,5,1,6,1,1,2,1179,2521,163,186,92,곳
44,5,1,6,1,1,3,1303,2532,82,102,96,을
45,5,1,6,1,1,4,1438,2540,260,102,93,이용해
46,2,1,7,0,0,0,1705,2554,293,93,-1,
47,3,1,7,1,0,0,1705,2554,293,93,-1,
48,4,1,7,1,1,0,1705,2554,293,93,-1,
49,5,1,7,1,1,1,1705,2554,148,93,92,수
50,5,1,7,1,1,2,1863,2562,72,77,89,세
51,5,1,7,1,1,3,1903,2550,64,101,93,요
52,5,1,7,1,1,4,1981,2564,17,62,92,!
53,2,1,8,0,0,0,2595,3475,141,6,-1,
54,3,1,8,1,0,0,2595,3475,141,6,-1,
55,4,1,8,1,1,0,2595,3475,141,6,-1,
56,5,1,8,1,1,1,2595,3475,141,6,28,SS
57,5,1,8,1,1,2,2684,3460,5,28,3,—
58,5,1,8,1,1,3,2729,3460,11,28,0,때

In [19]:
def get_bounding_box(img_data, padding=50):
    valids = []
    for le, to, wi, he, te in image_data[['left','top', 'width', 'height', 'text']].values.tolist():
        if te.strip()!='':
            valids.append((max(0,int(le)-padding), max(0,int(to)-padding), int(wi)+padding*2, int(he)+padding*2))
    return valids

In [20]:
bb = get_bounding_box(image_data)
bb

[(1474, 554, 267, 434),
 (491, 1550, 401, 169),
 (850, 1536, 229, 178),
 (1034, 1524, 606, 216),
 (1619, 1543, 260, 205),
 (1851, 1547, 484, 208),
 (2317, 1561, 386, 205),
 (981, 1793, 253, 195),
 (1182, 1812, 223, 173),
 (1355, 1806, 837, 221),
 (891, 2277, 248, 197),
 (1077, 2316, 147, 147),
 (1136, 2284, 187, 180),
 (1232, 2289, 115, 162),
 (1311, 2295, 233, 162),
 (1484, 2307, 153, 178),
 (1582, 2300, 148, 153),
 (1604, 2273, 151, 235),
 (1629, 2273, 152, 235),
 (1737, 2304, 272, 174),
 (1840, 2273, 168, 235),
 (2857, 2312, 125, 188),
 (2896, 2316, 106, 126),
 (1075, 2481, 236, 272),
 (1129, 2471, 263, 286),
 (1253, 2482, 182, 202),
 (1388, 2490, 360, 202),
 (1655, 2504, 248, 193),
 (1813, 2512, 172, 177),
 (1853, 2500, 164, 201),
 (1931, 2514, 117, 162),
 (2545, 3425, 241, 106),
 (2634, 3410, 105, 128),
 (2679, 3410, 111, 128)]

In [22]:
get_region = lambda image,l,t,w,h:image[t:t+h, l:l+w]

In [26]:
cv2.imshow('image', get_region(image, *bb[1]))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
import numpy as np

def mark_region(bbox_points, image_shape, flag='left-top-width-height'):
    if flag=='left-top-width-height':
        region = np.zeros(image_shape)
        for l,t,w,h in bbox_points:
            region[t:t+h, l:l+w] = 255
        return region

In [28]:
region = mark_region(bb, image.shape)
cv2.imwrite('./image/regions.jpg', region)

True

In [29]:
from itertools import chain


def merge_region(bbox_points, image_shape, flag='left-top-width-height'):
    if flag=='left-top-width-height':
        region = np.zeros(image_shape)
        for l,t,w,h in bbox_points:
            region[t:t+h, l:l+w] = 255
        top_bottom = []
        has_top = False
        for i,line in enumerate(region):
            if sum(line) > 0.:
                if not has_top:
                    top_bottom.append([i])
                    has_top=True
            else:
                if has_top:
                    top_bottom[-1].append(i)
                    has_top = False
        tblrs = []
        for top, bottom in top_bottom:
            left_right = []
            has_left = False
            obj = region[top:bottom, :]
            for j in range(region.shape[-1]):
                line = obj[:,j]
                if sum(line) > 0.:
                    if not has_left:
                        left_right.append([j])
                        has_left=True
                else:
                    if has_left:
                        left_right[-1].append(j)
                        has_left = False
            
            tbs = [[top,bottom]]*len(left_right)
            pairs = [(lr[0], tb[0],max(0,lr[1]-lr[0]), tb[1]-tb[0]) for tb,lr in zip(tbs, left_right)]
            tblrs.append(pairs)
        tblrs = list(chain(*tblrs))
        return tblrs

In [30]:
merged_bbox = merge_region(bb, image.shape)
merged_bbox

[(1474, 554, 267, 434),
 (491, 1524, 2212, 242),
 (981, 1793, 1211, 234),
 (891, 2273, 1157, 484),
 (2857, 2273, 145, 484),
 (2545, 3410, 245, 128)]

In [31]:
new_region = mark_region(merged_bbox, image.shape)
cv2.imwrite('./image/new_regions.jpg', new_region)

True

In [32]:
regions = [get_region(image, *bb) for bb in merged_bbox]

In [33]:
for region in regions:
    result = run_pytesseract(region, path_engine,config='-l eng+kor --oem 1 --psm 11')
    print(result)

wi-ri >> KT_GiGA_5G Wave2_2A1B
PW >> 8hg79eh832
필 요 하신 스 트 로 우 , 낸 키

이 곳 을 이용해

수 세 요 !