In [1]:
from pytesseract import pytesseract
from PIL import Image

In [2]:
def load_image(path, mode=''):
    return Image.open(path)

def run_pytesseract(image, path_engine, config= '-l eng'):
    pytesseract.tesseract_cmd = path_engine
    result = pytesseract.image_to_string(image, config=config)
    return result

In [3]:
path_engine = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
path_image ='./image/test.jpg'

run_pytesseract(load_image(path_image), path_engine)

'PW >> 8hg79eh832'

In [5]:
import pandas as pd

def image2data(path_img):
    data = pytesseract.image_to_data(path_img)
    lines = data.split('\n')
    columns, df_data = None, None
    for i,line in enumerate(lines):
        line = line.split('\t')
        if i==0:
            columns = line.copy()
            df_data = {col:[] for col in line}
            continue
        for col, l in zip(columns,line):
            df_data[col]+=[l]
    return pd.DataFrame(df_data)

In [6]:
image2data(path_image)

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,4032,3024,-1,
1,2,1,1,0,0,0,941,0,746,117,-1,
2,3,1,1,1,0,0,941,0,1091,117,-1,
3,4,1,1,1,1,0,941,0,746,117,-1,
4,5,1,1,1,1,1,941,0,746,117,47,|
...,...,...,...,...,...,...,...,...,...,...,...,...
99,5,1,10,1,1,1,0,2291,4032,733,95,
100,2,1,11,0,0,0,1561,2366,25,126,-1,
101,3,1,11,1,0,0,1561,2366,25,126,-1,
102,4,1,11,1,1,0,1561,2366,25,126,-1,
103,5,1,11,1,1,1,1561,2366,25,126,68,Raee

In [7]:
def image_to_osd(path_image):
    lines = pytesseract.image_to_osd(path_image).split('\n')
    lines = [line.strip().split(':') for line in lines]
    return {k.strip():v.strip() for k,v in lines}

In [8]:
image_to_osd(path_image)

{'Page number': '0',
 'Orientation in degrees': '180',
 'Rotate': '180',
 'Orientation confidence': '0.03',
 'Script': 'Cyrillic',
 'Script confidence': '0.48'}

In [9]:
def get_pdf(path_image, path_output):
    assert path_output.split('.')[-1]=='pdf', 'The ouput format should be the "pdf"'
    pdf = pytesseract.image_to_pdf_or_hocr(path_image, extension='pdf')
    with open(path_output, 'w+b') as f:
        f.write(pdf)
        print('saved successfully!')

In [10]:
get_pdf(path_image,'./result.pdf')

saved successfully!